openapi: 3.0.3
info:
  title: Trade Reporting Engine
  description: Trade Reporting Engine
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'

paths:
  /trade/reportingEngine/filtered:
    get:
      summary: Fetch filtered Entities from Database
      responses:
        200:
          description: Fetch filtered Entities from Database
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TradeEntity' # Reference to the Event

        500:
          description:  |
            1. Any technical errors
            2. Any errors while retrieving data

components:
  schemas:
    TradeEntity:
      type: object
      properties:
        id:
          type: integer
          format: int64
        buyerParty:
          type: string
        sellerParty:
          type: string
        premiumAmount:
          type: number
          format: BigDecimal
        premiumCurrency:
          type: string
      example:
        id: 1
        buyerParty: "BIC1"
        sellerParty: "EMU_BANK"
        premiumAmount: 100.0
        premiumCurrency: "AUD"
  
